// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	connectionsList: () => typedError<StoredConnection[], string>(__TAURI_INVOKE("connections_list")),
	connectionCreate: (draft: ConnectionDraft) => typedError<StoredConnection, string>(__TAURI_INVOKE("connection_create", { draft })),
	connectionUpdate: (id: string, draft: ConnectionDraft) => typedError<StoredConnection, string>(__TAURI_INVOKE("connection_update", { id, draft })),
	connectionSetFavorite: (id: string, isFavorite: boolean) => typedError<StoredConnection, string>(__TAURI_INVOKE("connection_set_favorite", { id, isFavorite })),
	connectionDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("connection_delete", { id })),
};

/* Types */
export type ConnectionDraft = {
	name: string,
	host: string,
	port: number,
	username: string,
};

export type StoredConnection = {
	id: string,
	name: string,
	host: string,
	port: number,
	username: string,
	isFavorite: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

