// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	connectionsList: () => typedError<StoredConnection[], string>(__TAURI_INVOKE("connections_list")),
	connectionCreate: (draft: ConnectionDraft) => typedError<StoredConnection, string>(__TAURI_INVOKE("connection_create", { draft })),
	connectionUpdate: (id: string, draft: ConnectionDraft) => typedError<StoredConnection, string>(__TAURI_INVOKE("connection_update", { id, draft })),
	connectionSetFavorite: (id: string, isFavorite: boolean) => typedError<StoredConnection, string>(__TAURI_INVOKE("connection_set_favorite", { id, isFavorite })),
	connectionDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("connection_delete", { id })),
	profilesList: () => typedError<Profile[], string>(__TAURI_INVOKE("profiles_list")),
	profileCreate: (draft: ProfileDraft, password: string | null) => typedError<Profile, string>(__TAURI_INVOKE("profile_create", { draft, password })),
	profileUpdate: (id: string, draft: ProfileDraft, password: string | null) => typedError<Profile, string>(__TAURI_INVOKE("profile_update", { id, draft, password })),
	profileDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("profile_delete", { id })),
	profileDeletePassword: (id: string) => typedError<null, string>(__TAURI_INVOKE("profile_delete_password", { id })),
	secretHasPassword: (connectionId: string) => __TAURI_INVOKE<boolean>("secret_has_password", { connectionId }),
	secretDeletePassword: (connectionId: string) => typedError<null, string>(__TAURI_INVOKE("secret_delete_password", { connectionId })),
	sshConnect: (params: ConnectParams) => typedError<ConnectOutcome, string>(__TAURI_INVOKE("ssh_connect", { params })),
	sshAuthenticatePassword: (sessionId: string, password: string, remember: boolean) => typedError<PasswordOutcome, string>(__TAURI_INVOKE("ssh_authenticate_password", { sessionId, password, remember })),
	sshHostKeyDecision: (sessionId: string, accept: boolean) => __TAURI_INVOKE<void>("ssh_host_key_decision", { sessionId, accept }),
	sshWrite: (sessionId: string, data: string) => __TAURI_INVOKE<void>("ssh_write", { sessionId, data }),
	sshResize: (sessionId: string, cols: number, rows: number) => __TAURI_INVOKE<void>("ssh_resize", { sessionId, cols, rows }),
	sshDisconnect: (sessionId: string) => __TAURI_INVOKE<void>("ssh_disconnect", { sessionId }),
	sftpReadDir: (sessionId: string, path: string) => typedError<SftpEntry[], string>(__TAURI_INVOKE("sftp_read_dir", { sessionId, path })),
	sftpHomeDir: (sessionId: string) => typedError<string, string>(__TAURI_INVOKE("sftp_home_dir", { sessionId })),
	sftpReadFile: (sessionId: string, path: string) => typedError<number[], string>(__TAURI_INVOKE("sftp_read_file", { sessionId, path })),
	sftpDownload: (sessionId: string, remotePath: string, localPath: string) => typedError<null, string>(__TAURI_INVOKE("sftp_download", { sessionId, remotePath, localPath })),
	sftpUploadPath: (sessionId: string, localPath: string, remoteDir: string) => typedError<null, string>(__TAURI_INVOKE("sftp_upload_path", { sessionId, localPath, remoteDir })),
	sftpRemove: (sessionId: string, path: string) => typedError<null, string>(__TAURI_INVOKE("sftp_remove", { sessionId, path })),
};

/** Events */
export const events = {
	hostKeyPrompt: makeEvent<HostKeyPrompt>("host-key-prompt"),
	sshClosed: makeEvent<SshClosed>("ssh-closed"),
	sshOutput: makeEvent<SshOutput>("ssh-output"),
};

/* Types */
export type ConnectOutcome = "connected" | "passwordRequired";

export type ConnectParams = {
	sessionId: string,
	connectionId: string,
	host: string,
	port: number,
	username: string,
	profileId: string | null,
	cols: number,
	rows: number,
};

export type ConnectionDraft = {
	name: string,
	host: string,
	port: number,
	username: string,
	profileId: string | null,
};

export type HostKeyPrompt = {
	sessionId: string,
	host: string,
	port: number,
	fingerprint: string,
	changed: boolean,
};

export type PasswordOutcome = "authenticated" | { failed: number } | "lockedOut";

export type Profile = {
	id: string,
	name: string,
	username: string,
	hasPassword: boolean,
};

export type ProfileDraft = {
	name: string,
	username: string,
};

export type SftpEntry = {
	name: string,
	path: string,
	kind: SftpKind,
	size: number | null,
	modified: number | null,
	mode: number | null,
};

export type SftpKind = "file" | "dir" | "symlink" | "other";

export type SshClosed = {
	sessionId: string,
	message: string | null,
};

export type SshOutput = {
	sessionId: string,
	data: number[],
};

export type StoredConnection = {
	id: string,
	name: string,
	host: string,
	port: number,
	username: string,
	isFavorite: boolean,
	profileId: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

