// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	connectionsList: () => typedError<StoredConnection[], string>(__TAURI_INVOKE("connections_list")),
	connectionCreate: (draft: ConnectionDraft) => typedError<StoredConnection, string>(__TAURI_INVOKE("connection_create", { draft })),
	connectionUpdate: (id: string, draft: ConnectionDraft) => typedError<StoredConnection, string>(__TAURI_INVOKE("connection_update", { id, draft })),
	connectionSetFavorite: (id: string, isFavorite: boolean) => typedError<StoredConnection, string>(__TAURI_INVOKE("connection_set_favorite", { id, isFavorite })),
	connectionDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("connection_delete", { id })),
	consoleConnectionsList: () => typedError<StoredConsoleConnection[], string>(__TAURI_INVOKE("console_connections_list")),
	consoleConnectionCreate: (draft: ConsoleConnectionDraft) => typedError<StoredConsoleConnection, string>(__TAURI_INVOKE("console_connection_create", { draft })),
	consoleConnectionUpdate: (id: string, draft: ConsoleConnectionDraft) => typedError<StoredConsoleConnection, string>(__TAURI_INVOKE("console_connection_update", { id, draft })),
	consoleConnectionSetFavorite: (id: string, isFavorite: boolean) => typedError<StoredConsoleConnection, string>(__TAURI_INVOKE("console_connection_set_favorite", { id, isFavorite })),
	consoleConnectionDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("console_connection_delete", { id })),
	profilesList: () => typedError<Profile[], string>(__TAURI_INVOKE("profiles_list")),
	profileCreate: (draft: ProfileDraft, password: string | null) => typedError<Profile, string>(__TAURI_INVOKE("profile_create", { draft, password })),
	profileUpdate: (id: string, draft: ProfileDraft, password: string | null) => typedError<Profile, string>(__TAURI_INVOKE("profile_update", { id, draft, password })),
	profileDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("profile_delete", { id })),
	profileDeletePassword: (id: string) => typedError<null, string>(__TAURI_INVOKE("profile_delete_password", { id })),
	profileSetDefault: (id: string, isDefault: boolean) => typedError<Profile, string>(__TAURI_INVOKE("profile_set_default", { id, isDefault })),
	secretHasPassword: (connectionId: string) => __TAURI_INVOKE<boolean>("secret_has_password", { connectionId }),
	secretDeletePassword: (connectionId: string) => typedError<null, string>(__TAURI_INVOKE("secret_delete_password", { connectionId })),
	terminalWrite: (sessionId: string, data: string) => __TAURI_INVOKE<void>("terminal_write", { sessionId, data }),
	terminalResize: (sessionId: string, cols: number, rows: number) => __TAURI_INVOKE<void>("terminal_resize", { sessionId, cols, rows }),
	sshConnect: (params: ConnectParams) => typedError<ConnectOutcome, string>(__TAURI_INVOKE("ssh_connect", { params })),
	sshAuthenticatePassword: (sessionId: string, password: string, remember: boolean) => typedError<PasswordOutcome, string>(__TAURI_INVOKE("ssh_authenticate_password", { sessionId, password, remember })),
	sshHostKeyDecision: (sessionId: string, accept: boolean) => __TAURI_INVOKE<void>("ssh_host_key_decision", { sessionId, accept }),
	/**
	 *  Closing an SSH session also drops any half-finished authentication: the user
	 *  may be cancelling from the password prompt, before a session ever existed.
	 */
	sshDisconnect: (sessionId: string) => __TAURI_INVOKE<void>("ssh_disconnect", { sessionId }),
	consoleListPorts: () => typedError<AvailablePort[], string>(__TAURI_INVOKE("console_list_ports")),
	consoleConnect: (params: ConsoleParams) => typedError<null, string>(__TAURI_INVOKE("console_connect", { params })),
	consoleDisconnect: (sessionId: string) => __TAURI_INVOKE<void>("console_disconnect", { sessionId }),
	sftpReadDir: (sessionId: string, path: string) => typedError<SftpEntry[], string>(__TAURI_INVOKE("sftp_read_dir", { sessionId, path })),
	sftpHomeDir: (sessionId: string) => typedError<string, string>(__TAURI_INVOKE("sftp_home_dir", { sessionId })),
	sftpReadFile: (sessionId: string, path: string) => typedError<number[], string>(__TAURI_INVOKE("sftp_read_file", { sessionId, path })),
	sftpDownload: (sessionId: string, remotePath: string, localPath: string) => typedError<null, string>(__TAURI_INVOKE("sftp_download", { sessionId, remotePath, localPath })),
	sftpUploadPath: (sessionId: string, localPath: string, remoteDir: string) => typedError<null, string>(__TAURI_INVOKE("sftp_upload_path", { sessionId, localPath, remoteDir })),
	sftpRemove: (sessionId: string, path: string) => typedError<null, string>(__TAURI_INVOKE("sftp_remove", { sessionId, path })),
};

/** Events */
export const events = {
	hostKeyPrompt: makeEvent<HostKeyPrompt>("host-key-prompt"),
	terminalClosed: makeEvent<TerminalClosed>("terminal-closed"),
	terminalOutput: makeEvent<TerminalOutput>("terminal-output"),
};

/* Types */
/**  A serial port the machine currently exposes. */
export type AvailablePort = {
	name: string,
	/**  What the OS knows about the device, to tell several adapters apart. */
	description: string | null,
};

export type ConnectOutcome = "connected" | "passwordRequired";

export type ConnectParams = {
	sessionId: string,
	connectionId: string,
	host: string,
	port: number,
	username: string,
	profileId: string | null,
	cols: number,
	rows: number,
};

/**
 *  What every saved connection carries, whatever transport it opens. SSH and
 *  console connections share nothing else, so they live in separate tables.
 */
export type ConnectionBase = {
	id: string,
	name: string,
	isFavorite: boolean,
};

export type ConnectionDraft = {
	name: string,
	host: string,
	port: number,
	username: string,
	profileId: string | null,
};

export type ConsoleConnectionDraft = {
	name: string,
	settings: SerialSettings,
};

export type ConsoleParams = {
	sessionId: string,
	settings: SerialSettings,
};

export type FlowControl = "none" | "hardware" | "software";

export type HostKeyPrompt = {
	sessionId: string,
	host: string,
	port: number,
	fingerprint: string,
	changed: boolean,
};

export type Parity = "none" | "odd" | "even";

export type PasswordOutcome = "authenticated" | { failed: number } | "lockedOut";

export type Profile = {
	id: string,
	name: string,
	username: string,
	hasPassword: boolean,
	isDefault: boolean,
};

export type ProfileDraft = {
	name: string,
	username: string,
};

/**
 *  Line settings for a console (serial) connection.
 * 
 *  Mark/space parity and 1.5 stop bits are absent on purpose: `serialport`
 *  exposes neither on any platform, and macOS has no termios route to them at
 *  all. Adding them needs a per-platform path plus a migration.
 */
export type SerialSettings = {
	portName: string,
	baudRate: number,
	dataBits: number,
	parity: Parity,
	stopBits: StopBits,
	flowControl: FlowControl,
};

export type SftpEntry = {
	name: string,
	path: string,
	kind: SftpKind,
	size: number | null,
	modified: number | null,
	mode: number | null,
};

export type SftpKind = "file" | "dir" | "symlink" | "other";

export type StopBits = "one" | "two";

export type StoredConnection = {
	host: string,
	port: number,
	username: string,
	profileId: string | null,
} & ConnectionBase;

export type StoredConsoleConnection = {
	settings: SerialSettings,
} & ConnectionBase;

export type TerminalClosed = {
	sessionId: string,
	message: string | null,
};

export type TerminalOutput = {
	sessionId: string,
	data: number[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

